package com.example.tfgsportpro.features.f01_Home.domain.routines

import com.example.tfgsportpro.features.f01_Home.domain.model.Exercise
import com.example.tfgsportpro.features.f01_Home.domain.model.HighIntensityExercises

class HighRoutine {

    fun getRoutineForDayHigh(day: Int): List<Exercise> {
        return when (day) {
            1 -> listOf(
                HighIntensityExercises.highKneesHigh,
                HighIntensityExercises.pushUpToeTouchHigh,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.intenseJumpingSquatsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.bicycleCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.clapPushUpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralJumpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyPushUpHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.splitSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.plankWithShoulderTapHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.supermanHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.vCrunchesHigh
            )
            2 -> listOf(
                HighIntensityExercises.pushUpToeTouchHigh,
                HighIntensityExercises.plyoJacksHigh,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.controlledPushupsSlowHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.jumpingLungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.navySealBurpeeHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.skaterSquat,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.burpeesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.gluteBridgeHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.reversePlankHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.hawaiianSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.singleLegSquatsHigh
            )
            3 -> listOf(
                HighIntensityExercises.plyoJacksHigh,
                HighIntensityExercises.boxing,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.sumoSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.shortCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralLungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.archerPushUpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lLegRaisesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.sprintInPlaceHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.weightedRussianTwistsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.climbersHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.singleLegPlankHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossoverLungesHigh
            )
            4 -> listOf(
                HighIntensityExercises.boxing,
                HighIntensityExercises.bearCrawl,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.burpeesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.intenseJumpingSquatsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.plankLegRaisesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.heelTapCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.controlledPushupsSlowHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.supermanHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.hawaiianSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralJumpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.weightedRussianTwistsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.navySealBurpeeHigh
            )
            5 -> listOf(
                HighIntensityExercises.bearCrawl,
                HighIntensityExercises.jumpingJacksHigh,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossoverLungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.shrimpSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.vCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.plankWithShoulderTapHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.clapPushUpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.singleLegSquatsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyPushUpHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.splitSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crunches90DegreesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralLungesHigh
            )
            6 -> listOf(
                HighIntensityExercises.jumpingJacksHigh,
                HighIntensityExercises.verticalMountainClimberHigh,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.burpeesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.bicycleCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.climbersHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.sumoSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.supermanHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.singleLegPlankHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.hawaiianSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.weightedRussianTwistsHigh
            )
            7 -> listOf(
                HighIntensityExercises.verticalMountainClimberHigh,
                HighIntensityExercises.highKneesHigh,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.intenseJumpingSquatsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.plankOneArmLegHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.splitSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.navySealBurpeeHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralJumpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.reversePlankHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.clapPushUpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.vCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.jumpingLungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lLegRaisesHigh
            )
            8 -> listOf(
                HighIntensityExercises.highKneesHigh,
                HighIntensityExercises.pushUpToeTouchHigh,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralLungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.shortCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.singleLegSquatsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.burpeesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.plankWithShoulderTapHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.sprintInPlaceHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyPushUpHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.heelTapCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.gluteBridgeHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyCrunchesHigh
            )
            9 -> listOf(
                HighIntensityExercises.pushUpToeTouchHigh,
                HighIntensityExercises.plyoJacksHigh,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.crunches90DegreesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralJumpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.jumpingLungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.clapPushUpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.singleLegPlankHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.shrimpSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.splitSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.supermanHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.navySealBurpeeHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.burpeesHigh
            )
            10 -> listOf(
                HighIntensityExercises.plyoJacksHigh,
                HighIntensityExercises.boxing,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.skaterSquat,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.weightedRussianTwistsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.plankLegRaisesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyPushUpHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.hawaiianSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.climbersHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.sumoSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.vCrunchesHigh
            )
            11 -> listOf(
                HighIntensityExercises.boxing,
                HighIntensityExercises.bearCrawl,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralLungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.controlledPushupsSlowHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.splitSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.navySealBurpeeHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.sprintInPlaceHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.clapPushUpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.supermanHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.archerPushUpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.gluteBridgeHigh
            )
            12 -> listOf(
                HighIntensityExercises.bearCrawl,
                HighIntensityExercises.jumpingJacksHigh,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.plankWithShoulderTapHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyPushUpHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.shortCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralJumpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.singleLegSquatsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.bicycleCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.burpeesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.heelTapCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.hawaiianSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.supermanHigh
            )
            13 -> listOf(
                HighIntensityExercises.jumpingJacksHigh,
                HighIntensityExercises.verticalMountainClimberHigh,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossoverLungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralLungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lLegRaisesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.plankOneArmLegHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.reversePlankHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.clapPushUpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyPushUpHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.sumoSquatHigh
            )
            14 -> listOf(
                HighIntensityExercises.bearCrawl,
                HighIntensityExercises.boxing,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.singleLegPlankHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.shrimpSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.splitSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.gluteBridgeHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.weightedRussianTwistsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.navySealBurpeeHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.archerPushUpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.supermanHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.burpeesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.climbersHigh
            )
            15 -> listOf(
                HighIntensityExercises.plyoJacksHigh,
                HighIntensityExercises.pushUpToeTouchHigh,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyCrunchesHigh ,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.bicycleCrunchesHigh ,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.singleLegSquatsHigh ,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.plankOneArmLegHigh ,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.hawaiianSquatHigh ,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.sumoSquatHigh ,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.plankWithShoulderTapHigh ,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lLegRaisesHigh ,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyPushUpHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralLungesHigh
            )
            /////////A partir de aqui son repetidas las rutinas del 1 al 15///////
            16 -> listOf(
                HighIntensityExercises.highKneesHigh,
                HighIntensityExercises.pushUpToeTouchHigh,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.intenseJumpingSquatsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.bicycleCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.clapPushUpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralJumpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyPushUpHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.splitSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.plankWithShoulderTapHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.supermanHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.vCrunchesHigh
            )
            17 -> listOf(
                HighIntensityExercises.pushUpToeTouchHigh,
                HighIntensityExercises.plyoJacksHigh,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.controlledPushupsSlowHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.jumpingLungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.navySealBurpeeHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.skaterSquat,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.burpeesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.gluteBridgeHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.reversePlankHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.hawaiianSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.singleLegSquatsHigh
            )
            18 -> listOf(
                HighIntensityExercises.plyoJacksHigh,
                HighIntensityExercises.boxing,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.sumoSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.shortCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralLungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.archerPushUpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lLegRaisesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.sprintInPlaceHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.weightedRussianTwistsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.climbersHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.singleLegPlankHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossoverLungesHigh
            )
            19 -> listOf(
                HighIntensityExercises.boxing,
                HighIntensityExercises.bearCrawl,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.burpeesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.intenseJumpingSquatsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.plankLegRaisesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.heelTapCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.controlledPushupsSlowHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.supermanHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.hawaiianSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralJumpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.weightedRussianTwistsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.navySealBurpeeHigh
            )
            20 -> listOf(
                HighIntensityExercises.bearCrawl,
                HighIntensityExercises.jumpingJacksHigh,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossoverLungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.shrimpSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.vCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.plankWithShoulderTapHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.clapPushUpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.singleLegSquatsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyPushUpHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.splitSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crunches90DegreesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralLungesHigh
            )
            21 -> listOf(
                HighIntensityExercises.jumpingJacksHigh,
                HighIntensityExercises.verticalMountainClimberHigh,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.burpeesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.bicycleCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.climbersHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.sumoSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.supermanHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.singleLegPlankHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.hawaiianSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.weightedRussianTwistsHigh
            )
            22 -> listOf(
                HighIntensityExercises.verticalMountainClimberHigh,
                HighIntensityExercises.highKneesHigh,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.intenseJumpingSquatsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.plankOneArmLegHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.splitSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.navySealBurpeeHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralJumpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.reversePlankHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.clapPushUpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.vCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.jumpingLungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lLegRaisesHigh
            )
            23 -> listOf(
                HighIntensityExercises.highKneesHigh,
                HighIntensityExercises.pushUpToeTouchHigh,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralLungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.shortCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.singleLegSquatsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.burpeesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.plankWithShoulderTapHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.sprintInPlaceHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyPushUpHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.heelTapCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.gluteBridgeHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyCrunchesHigh
            )
            24 -> listOf(
                HighIntensityExercises.pushUpToeTouchHigh,
                HighIntensityExercises.plyoJacksHigh,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.crunches90DegreesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralJumpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.jumpingLungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.clapPushUpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.singleLegPlankHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.shrimpSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.splitSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.supermanHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.navySealBurpeeHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.burpeesHigh
            )
            25 -> listOf(
                HighIntensityExercises.plyoJacksHigh,
                HighIntensityExercises.boxing,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.skaterSquat,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.weightedRussianTwistsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.plankLegRaisesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyPushUpHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.hawaiianSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.climbersHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.sumoSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.vCrunchesHigh
            )
            26 -> listOf(
                HighIntensityExercises.boxing,
                HighIntensityExercises.bearCrawl,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralLungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.controlledPushupsSlowHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.splitSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.navySealBurpeeHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.sprintInPlaceHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.clapPushUpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.supermanHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.archerPushUpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.gluteBridgeHigh
            )
            27 -> listOf(
                HighIntensityExercises.bearCrawl,
                HighIntensityExercises.jumpingJacksHigh,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.plankWithShoulderTapHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyPushUpHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.shortCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralJumpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.singleLegSquatsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.bicycleCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.burpeesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.heelTapCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.hawaiianSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.supermanHigh
            )
            28 -> listOf(
                HighIntensityExercises.jumpingJacksHigh,
                HighIntensityExercises.verticalMountainClimberHigh,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossoverLungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralLungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lLegRaisesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.plankOneArmLegHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.reversePlankHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lungesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.clapPushUpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyCrunchesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyPushUpHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.sumoSquatHigh
            )
            29 -> listOf(
                HighIntensityExercises.bearCrawl,
                HighIntensityExercises.boxing,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.singleLegPlankHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.shrimpSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.splitSquatHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.gluteBridgeHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.weightedRussianTwistsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.navySealBurpeeHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.archerPushUpsHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.supermanHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.burpeesHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.climbersHigh
            )
            30 -> listOf(
                HighIntensityExercises.plyoJacksHigh,
                HighIntensityExercises.pushUpToeTouchHigh,

                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyCrunchesHigh ,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.bicycleCrunchesHigh ,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.singleLegSquatsHigh ,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.plankOneArmLegHigh ,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.hawaiianSquatHigh ,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.sumoSquatHigh ,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.plankWithShoulderTapHigh ,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lLegRaisesHigh ,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyPushUpHigh,
                HighIntensityExercises.BREAK,
                HighIntensityExercises.lateralLungesHigh
            )
            else -> emptyList()
        }
    }
}