package com.example.tfgsportpro.features.f01_Home.domain.routines

import com.example.tfgsportpro.features.f01_Home.domain.model.Exercise
import com.example.tfgsportpro.features.f01_Home.domain.model.HighIntensityExercises
import com.example.tfgsportpro.features.f01_Home.domain.model.LowIntensityExercises

class MediumRoutine {

    fun getRoutineForDayMedium(day: Int): List<Exercise> {
        return when (day) {
            1 -> listOf(
                LowIntensityExercises.highKnees,
                LowIntensityExercises.jumpingJacks,

                HighIntensityExercises.controlledPushupsSlowHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.basicCrunches,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.jumpingLungesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.stepUps,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.burpeesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.heelRaises,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.climbersHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.squats,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.plankWithShoulderTapHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.superman
            )
            2 -> listOf(
                LowIntensityExercises.lowSkipping,
                LowIntensityExercises.jumpingSquats,

                HighIntensityExercises.clapPushUpsHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.pushUps,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.vCrunchesHigh,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.supermanHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.russianTwists,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.burpeesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.plank,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.singleLegPlankHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.basicCrunches,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.weightedRussianTwistsHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.gluteBridge
            )
            3 -> listOf(
                LowIntensityExercises.plyoJacks,
                HighIntensityExercises.boxing,

                HighIntensityExercises.jumpingJacksHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.jumpingSquats,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.squatWithPauseHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.lateralLegRaise,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.clapPushUpsHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.heelRaises,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.sumoSquatHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.basicCrunches,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.plankWithShoulderTapHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.stepUps
            )
            4 -> listOf(
                HighIntensityExercises.verticalMountainClimberHigh,
                LowIntensityExercises.jumpingSquats,

                HighIntensityExercises.plyoJacksHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.pushUps,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.controlledPushupsSlowHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.squats,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.climbersHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.plank,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.lateralJumpsHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.heelRaisesOnStep,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.jumpingLungesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.russianTwists
            )
            5 -> listOf(
                LowIntensityExercises.plyoJacks,
                HighIntensityExercises.boxing,

                HighIntensityExercises.burpeesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.heelRaises,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.lungesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.lateralLegRaise,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.weightedRussianTwistsHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.stepUps,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.highKneesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.basicCrunches,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.boxing,////////
                LowIntensityExercises.BREAK,
                LowIntensityExercises.squats
            )
            6 -> listOf(
                LowIntensityExercises.lowSkipping,
                LowIntensityExercises.jumpingSquats,

                HighIntensityExercises.squatWithPauseHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.pushUps,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.vCrunchesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.russianTwists,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.burpeesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.plank,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.singleLegPlankHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.basicCrunches,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.weightedRussianTwistsHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.gluteBridge
            )
            7 -> listOf(
                LowIntensityExercises.plyoJacks,
                HighIntensityExercises.boxing,

                HighIntensityExercises.jumpingJacksHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.jumpingSquats,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.squatWithPauseHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.lateralLegRaise,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.clapPushUpsHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.heelRaises,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.sumoSquatHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.basicCrunches,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.plankWithShoulderTapHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.stepUps
            )
            8 -> listOf(
                HighIntensityExercises.verticalMountainClimberHigh,
                LowIntensityExercises.jumpingSquats,

                HighIntensityExercises.plyoJacksHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.pushUps,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.controlledPushupsSlowHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.squats,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.climbersHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.plank,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.lateralJumpsHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.heelRaisesOnStep,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.jumpingLungesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.russianTwists
            )
            9 -> listOf(
                LowIntensityExercises.plyoJacks,
                HighIntensityExercises.boxing,

                HighIntensityExercises.burpeesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.heelRaises,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.lungesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.lateralLegRaise,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.weightedRussianTwistsHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.stepUps,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.highKneesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.basicCrunches,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.boxing,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.squats
            )
            10 -> listOf(
                LowIntensityExercises.lowSkipping,
                LowIntensityExercises.jumpingSquats,

                HighIntensityExercises.squatWithPauseHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.pushUps,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.vCrunchesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.russianTwists,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.burpeesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.plank,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.singleLegPlankHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.basicCrunches,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.weightedRussianTwistsHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.gluteBridge
            )
            11 -> listOf(
                LowIntensityExercises.jumpingSquats,
                HighIntensityExercises.bearCrawl,

                LowIntensityExercises.BREAK,
                HighIntensityExercises.bulgarianSplitSquatHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.pushUps,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.singleLegSquatsHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.plank,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.burpeesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.shortCrunches,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.lungesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.superman,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.weightedRussianTwistsHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.gluteBridge
            )
            12 -> listOf(
                HighIntensityExercises.bearCrawl,
                LowIntensityExercises.highKnees,

                LowIntensityExercises.BREAK,
                HighIntensityExercises.clapPushUpsHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.jumpingLunges,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.plankWithShoulderTapHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.catLegRaises,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.vCrunchesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.sidePlank,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.sumoSquatHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.lateralLegRaise,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.bicycleCrunchesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.kneePushUps
            )
            13 -> listOf(
                LowIntensityExercises.jumpingSquats,
                LowIntensityExercises.plyoJacks,

                LowIntensityExercises.BREAK,
                HighIntensityExercises.lateralPlankWalkHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.pushUps,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.jumpingLungesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.catLegRaises,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.sumoSquatHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.basicCrunches,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.hawaiianSquatHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.gluteBridge,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.crossBodyPushUpHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.heelRaisesOnStep
            )
            14 -> listOf(
                HighIntensityExercises.boxing,
                HighIntensityExercises.verticalMountainClimberHigh,

                LowIntensityExercises.BREAK,
                HighIntensityExercises.clapPushUpsHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.elbowPlank,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.singleLegSquatsHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.crossBodyCrunches,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.verticalMountainClimberHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.russianTwists,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.crossoverLungesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.squats,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.burpeesHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.gluteBridge
            )
            15 -> listOf(
                HighIntensityExercises.pushUpToeTouchHigh,
                HighIntensityExercises.verticalMountainClimberHigh,

                LowIntensityExercises.BREAK,
                HighIntensityExercises.singleLegPlankHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.jumpingLunges,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.bulgarianSplitSquatHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.superman,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.sprintInPlaceHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.kneePushUps,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.lateralJumpsHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.sidePlank,
                LowIntensityExercises.BREAK,
                HighIntensityExercises.splitSquatHigh,
                LowIntensityExercises.BREAK,
                LowIntensityExercises.stepUps
            )
            else -> listOf()
        }
    }
}
