package com.example.tfgsportpro.features.f01_Home.domain.model

import com.example.tfgsportpro.R

class Exercise(
    val nombreResId: Int,
    val duracion: Int = 30,
    val gifResId: Int? = null
)

object LowIntensityExercises {
    //Calentamientos
    val highKnees = Exercise(R.string.high_Knees, 30, R.drawable.e_high_knees_unscreen)
    val jumpingJacks = Exercise(R.string.jumping_Jacks, 30, R.drawable.e_jumping_jacks_unscreen)
    val jumpingSquats = Exercise(R.string.jumping_Squats, 30, R.drawable.e_jumping_squats_unscreen)
    val plyoJacks = Exercise(R.string.plyo_Jacks, 30, R.drawable.e_plyo_jacks_unscreen)
    val lowSkipping = Exercise(R.string.low_Skipping, 30, R.drawable.e_low_skipping_unscreen)
    //Ejercicios
    val BREAK = Exercise(R.string.BREAK, 30, R.drawable.e_break_unscreen)
    val lunges = Exercise(R.string.lunges, 30, R.drawable.e_lunges_unscreen)
    val heelRaises = Exercise(R.string.heel_Raises, 30, R.drawable.e_heel_raises_unscreen)
    val kneePushUps = Exercise(R.string.knee_Push_Ups, 30, R.drawable.e_knee_push_ups_unscreen)
    val russianTwists = Exercise(R.string.russian_Twists, 30, R.drawable.e_russian_twists_unscreen)
    val sidePlank = Exercise(R.string.side_Plank, 30, R.drawable.e_lateral_plank_unscreen)
    val basicCrunches = Exercise(R.string.crunches, 30, R.drawable.e_crunches_unscreen)
    val superman = Exercise(R.string.superman, 30, R.drawable.e_superman_unscreen)
    val squats = Exercise(R.string.squats, 30, R.drawable.e_squats_unscreen)
    val stepUps = Exercise(R.string.step_Ups, 30, R.drawable.e_step_ups_unscreen)
    val gluteBridge = Exercise(R.string.glute_Bridge, 30, R.drawable.e_glute_bridge_unscreen)
    val elbowPlank = Exercise(R.string.elbow_Plank, 30, R.drawable.e_elbow_plank_unscren)
    val climber = Exercise(R.string.climbers, 30, R.drawable.e_climbers_unscreen)
    val singleLegGluteBridge = Exercise(R.string.single_Leg_Glute_Bridge, 30, R.drawable.e_single_leg_glute_unscreen)
    val deadBug = Exercise(R.string.dead_Bug, 30, R.drawable.e_dead_bug_unscreen)
    val bicycleCrunches = Exercise(R.string.bicycle_Crunches, 30, R.drawable.e_bicycle_crunches_unscreen)
    val lateralLegRaise = Exercise(R.string.lateral_Leg_Raise, 30, R.drawable.e_lateral_leg_raise_unscreen)
    val lyingLegExtension = Exercise(R.string.lying_Leg_Extension, 30, R.drawable.e_lying_leg_extension_unscreen)
    val heelRaisesOnStep = Exercise(R.string.heel_Raises_On_Step, 30)
    val lateralJumps = Exercise(R.string.lateral_Jumps, 30, R.drawable.e_lateral_jumps_unscreen)
    val lateralLunges = Exercise(R.string.lateral_Lunges, 30, R.drawable.e_lateral_lunges_unscreen)
    val plank = Exercise(R.string.plank, 30, R.drawable.e_plank_hands_unscreen)
    val catLegRaises = Exercise(R.string.cat_Leg_Raises, 30, R.drawable.e_cat_leg_raises_unscreen)
    val reverseLunges = Exercise(R.string.reverse_Lunges, 30, R.drawable.e_reverse_lunge_unscreen)
    val pushUps = Exercise(R.string.push_Ups, 30, R.drawable.e_basic_push_up_unscreen)
    val lateralSquat = Exercise(R.string.lateral_Squat, 30, R.drawable.e_lateral_squat_unscreen)
    val jumpingLunges = Exercise(R.string.jumping_Lunges, 30, R.drawable.e_jumping_lunges_unscreen)
    val crossBodyCrunches = Exercise(R.string.cross_Body_crunches, 30, R.drawable.e_cross_body_crunches_unscreen)
    val shortCrunches = Exercise(R.string.short_Crunches, 30, R.drawable.e_short_crunches_unscreen)
}

object HighIntensityExercises {
    //Calentamientos
    val highKneesHigh = Exercise(R.string.high_Knees, 35, R.drawable.e_high_knees_unscreen)
    val pushUpToeTouchHigh = Exercise(R.string.push_Ups_Toe_Touch, 35, R.drawable.e_push_ups_toe_touch_unscreen)
    val plyoJacksHigh = Exercise(R.string.plyo_Jacks, 35, R.drawable.e_plyo_jacks_unscreen)
    val boxing = Exercise (R.string.boxing, 35, R.drawable.e_boxing_unscreen)
    val bearCrawl = Exercise(R.string.bear_Crawl, 35, R.drawable.e_bear_crawl_unscreen)
    val jumpingJacksHigh = Exercise(R.string.jumping_Jacks, 35, R.drawable.e_jumping_jacks_unscreen)
    val verticalMountainClimberHigh = Exercise(R.string.vertical_Mountain_Climbers, 35 , R.drawable.e_vertical_mountain_climber_unscreen)
    //Ejercicios
    val BREAK = Exercise(R.string.BREAK, 30, R.drawable.e_break_unscreen)
    val intenseJumpingSquatsHigh = Exercise(R.string.intense_Jumping_Squats, 35, R.drawable.e_jumping_squats_unscreen)
    val controlledPushupsSlowHigh = Exercise(R.string.controlled_Pushups_Slow, 35, R.drawable.e_controlled_push_ups_unscreen)
    val bicycleCrunchesHigh = Exercise(R.string.bicycle_Crunches, 35, R.drawable.e_bicycle_crunches_unscreen)
    val jumpingLungesHigh = Exercise(R.string.jumping_Lunges, 35, R.drawable.e_jumping_lunges_unscreen)
    val sprintInPlaceHigh = Exercise(R.string.sprint_In_Place, 35, R.drawable.e_run_in_place_unscreen)
    val burpeesHigh = Exercise(R.string.burpees, 35, R.drawable.e_burpee_unscreen)
    val climbersHigh = Exercise(R.string.climbers, 35, R.drawable.e_climbers_unscreen)
    val plankWithShoulderTapHigh = Exercise(R.string.plank_With_Shoulder_Tap, 35, R.drawable.e_plank_shoulder_touch_unscreen)
    val weightedRussianTwistsHigh = Exercise(R.string.weighted_Russian_Twists, 35, R.drawable.e_weight_russian_twits_unscreen)
    val gluteBridgeHigh = Exercise(R.string.glute_Bridge, 35, R.drawable.e_glute_bridge_unscreen)
    val clapPushUpsHigh = Exercise(R.string.clap_Push_Ups, 35, R.drawable.e_clapping_push_ups_unscreen)
    val lungesHigh = Exercise(R.string.lunges, 35, R.drawable.e_lunges_unscreen)
    val vCrunchesHigh = Exercise(R.string.v_Crunches, 35, R.drawable.e_v_crunches_unscreen)
    val singleLegPlankHigh = Exercise(R.string.single_Leg_Plank, 35, R.drawable.e_single_leg_plank_unscreen)
    val crossoverLungesHigh = Exercise(R.string.crossover_Lunges, 35, R.drawable.e_crossover_lunges_unscreen)
    val plankLegRaisesHigh = Exercise(R.string.plank_Leg_Raises, 35, R.drawable.e_plank_leg_raise_unscreen)
    val lateralPlankWalkHigh = Exercise(R.string.lateral_Plank_Walk, 35)
    val explosivePushUpsHigh = Exercise(R.string.explosive_Push_Ups, 35)
    val lLegRaisesHigh = Exercise(R.string.l_Leg_Raises, 35, R.drawable.e_l_leg_raises_unscreen)
    val supermanHigh = Exercise(R.string.superman, 35, R.drawable.e_superman_unscreen)
    val splitSquat = Exercise(R.string.split_Squat, 35, R.drawable.e_split_squat_unscreen)
    val squatWithPauseHigh = Exercise(R.string.squat_with_pause, 35)
    val shortCrunchesHigh = Exercise(R.string.short_Crunches, 35, R.drawable.e_short_crunches_unscreen)
    val heelTapCrunchesHigh = Exercise(R.string.heel_Tap_Crunches, 35, R.drawable.e_heel_tap_crunches_unscreen)
    val isometricSquatHigh = Exercise(R.string.isometric_squat, 35)
    val singleLegSquatsHigh = Exercise(R.string.single_leg_squat, 35, R.drawable.e_single_leg_squat_unscreen)
    val crossBodyCrunchesHigh = Exercise(R.string.cross_Body_crunches, 35)
    val plankAlternateKneeTapsHigh = Exercise(R.string.plank_Alternate_Knee_Taps, 35)
    val fastLungesHigh = Exercise(R.string.fast_Lunges, 35)
    val lateralJumpsHigh = Exercise(R.string.lateral_Jumps, 35)
    val sumoSquatHigh = Exercise(R.string.sumo_squat, 35)
    val bulgarianSplitSquatHigh = Exercise(R.string.bulgarian_split_squat, 35, R.drawable.e_bulgarian_squat_unscreen)
    val crunches90DegreesHigh = Exercise(R.string.crunches_90_Degrees, 35)
    val lateralLungesHigh = Exercise(R.string.lateral_Lunges, 35)
    val archerPushUpsHigh = Exercise(R.string.archer_Push_Ups, 35, R.drawable.e_archer_push_up_unscreen)
    val plankOneArmLeg = Exercise(R.string.plank_One_Arm_Leg, 35, R.drawable.e_front_plank_one_arm_leg_unscreen)
}