package com.example.tfgsportpro.features.f01_Home.fragments.trainingPage.trainingLevels.routines.exercises

import com.example.tfgsportpro.R

class Exercise(
    val nombreResId: Int,
    val duracion: Int = 30,
    val gifResId: Int? = null
)

object LowIntensityExercises {
    //Calentamientos
    val highKnees = Exercise(R.string.high_Knees, 30, R.drawable.e_high_knees)
    val jumpingJacks = Exercise(R.string.jumping_Jacks, 30, R.drawable.e_jumping_jacks)
    val jumpingSquats = Exercise(R.string.jumping_Squats, 30, R.drawable.e_jumping_squats)
    val jumpingInPlace = Exercise(R.string.jumping_In_Place, 30)
    val lowSkipping = Exercise(R.string.low_Skipping, 30, R.drawable.e_low_skipping)
    //Ejercicios
    val BREAK = Exercise(R.string.BREAK, 30, R.drawable.e_break)
    val lunges = Exercise(R.string.lunges, 30, R.drawable.e_lunges)
    val heelRaises = Exercise(R.string.heel_Raises, 30, R.drawable.e_heel_raises)
    val kneePushUps = Exercise(R.string.knee_Push_Ups, 30, R.drawable.e_knee_push_ups)
    val russianTwists = Exercise(R.string.russian_Twists, 30, R.drawable.e_russian_twists)
    val sidePlank = Exercise(R.string.side_Plank, 30, R.drawable.e_lateral_plank_unscreen)
    val basicCrunches = Exercise(R.string.crunches, 30, R.drawable.e_crunches_unscreen)
    val superman = Exercise(R.string.superman, 30, R.drawable.e_superman)
    val squats = Exercise(R.string.squats, 30, R.drawable.e_squats)
    val stepUps = Exercise(R.string.step_Ups, 30, R.drawable.e_step_ups)
    val gluteBridge = Exercise(R.string.glute_Bridge, 30, R.drawable.e_glute_bridge)
    val elbowPlank = Exercise(R.string.elbow_Plank, 30, R.drawable.e_elbow_plank)
    val climber = Exercise(R.string.climbers, 30, R.drawable.e_climbers_unscreen)
    val singleLegGluteBridge = Exercise(R.string.single_Leg_Glute_Bridge, 30, R.drawable.e_single_leg_glute)
    val deadBug = Exercise(R.string.dead_Bug, 30, R.drawable.e_dead_bug)
    val bicycleCrunches = Exercise(R.string.bicycle_Crunches, 30, R.drawable.e_bicycle_crunches_unscreen)
    val lateralLegRaise = Exercise(R.string.lateral_Leg_Raise, 30, R.drawable.e_lateral_leg_raise_unscreen)
    val lyingLegExtension = Exercise(R.string.lying_Leg_Extension, 30, R.drawable.e_lying_leg_extension_unscreen)
    val heelRaisesOnStep = Exercise(R.string.heel_Raises_On_Step, 30)
    val lateralJumps = Exercise(R.string.lateral_Jumps, 30, R.drawable.e_lateral_jumps_unscreen)
    val lateralLunges = Exercise(R.string.lateral_Lunges, 30)
    val plank = Exercise(R.string.plank, 30, R.drawable.e_plank)
    val catLegRaises = Exercise(R.string.cat_Leg_Raises, 30)
    val reverseLunges = Exercise(R.string.reverse_Lunges, 30)
    val pushUps = Exercise(R.string.push_Ups, 30, R.drawable.e_push_ups)
    val lateralSquat = Exercise(R.string.lateral_Squat, 30)
    val jumpingLunges = Exercise(R.string.jumping_Lunges, 30)
    val crossBodyCrunches = Exercise(R.string.cross_Body_crunches, 30)
    val shortCrunches = Exercise(R.string.short_Crunches, 30)
}

object HighIntensityExercises {
    //Calentamientos
    val highKneesHigh = Exercise(R.string.high_Knees, 35, R.drawable.e_high_knees)
    val highSkippingHigh = Exercise(R.string.high_Skipping, 35)
    val jumpingInPlaceHigh = Exercise(R.string.jumping_In_Place, 35)
    val intenseJumpingJacksHigh = Exercise(R.string.intense_Jumping_Jacks, 35)
    val jumpingJacksHigh = Exercise(R.string.jumping_Jacks, 35, R.drawable.e_jumping_jacks)
    val dynamicSquatsHigh = Exercise(R.string.dynamic_Squats, 35)
    //Ejercicios
    val BREAK = Exercise(R.string.BREAK, 30, R.drawable.e_break)
    val intenseJumpingSquatsHigh = Exercise(R.string.intense_Jumping_Squats, 35)
    val jumpingSquatsHigh = Exercise(R.string.jumping_Squats, 35)
    val controlledPushupsSlowHigh = Exercise(R.string.controlled_Pushups_Slow, 35)
    val bicycleCrunchesHigh = Exercise(R.string.bicycle_Crunches, 35)
    val jumpingLungesHigh = Exercise(R.string.jumping_Lunges, 35)
    val sprintInPlaceHigh = Exercise(R.string.sprint_In_Place, 35)
    val burpeesHigh = Exercise(R.string.burpees, 35, R.drawable.e_burpee)
    val climbersHigh = Exercise(R.string.climbers, 35)
    val plankWithShoulderTapHigh = Exercise(R.string.plank_With_Shoulder_Tap, 35)
    val weightedRussianTwistsHigh = Exercise(R.string.weighted_Russian_Twists, 35)
    val gluteBridgeHigh = Exercise(R.string.glute_Bridge, 35)
    val clapPushUpsHigh = Exercise(R.string.clap_Push_Ups, 35)
    val lungesHigh = Exercise(R.string.lunges, 35)
    val vCrunchesHigh = Exercise(R.string.v_Crunches, 35)
    val singleLegPlankHigh = Exercise(R.string.single_Leg_Plank, 35)
    val crossoverLungesHigh = Exercise(R.string.crossover_Lunges, 35)
    val plankLegRaisesHigh = Exercise(R.string.plank_Leg_Raises, 35)
    val lateralPlankWalkHigh = Exercise(R.string.lateral_Plank_Walk, 35)
    val explosivePushUpsHigh = Exercise(R.string.explosive_Push_Ups, 35)
    val lLegRaisesHigh = Exercise(R.string.l_Leg_Raises, 35)
    val supermanHigh = Exercise(R.string.superman, 35)
    val heelToGluteHigh = Exercise(R.string.heel_To_Glute, 35)
    val squatWithPauseHigh = Exercise(R.string.squat_with_pause, 35)
    val shortCrunchesHigh = Exercise(R.string.short_Crunches, 35)
    val heelTapCrunchesHigh = Exercise(R.string.heel_Tap_Crunches, 35, R.drawable.e_heel_tap_crunches)
    val isometricSquatHigh = Exercise(R.string.isometric_squat, 35)
    val singleLegSquatsHigh = Exercise(R.string.single_leg_squat, 35)
    val crossBodyCrunchesHigh = Exercise(R.string.cross_Body_crunches, 35)
    val plankAlternateKneeTapsHigh = Exercise(R.string.plank_Alternate_Knee_Taps, 35)
    val fastLungesHigh = Exercise(R.string.fast_Lunges, 35)
    val lateralJumpsHigh = Exercise(R.string.lateral_Jumps, 35)
    val sumoSquatHigh = Exercise(R.string.sumo_squat, 35)
    val bulgarianSplitSquatHigh = Exercise(R.string.bulgarian_split_squat, 35)
    val crunches90DegreesHigh = Exercise(R.string.crunches_90_Degrees, 35)
    val lateralLungesHigh = Exercise(R.string.lateral_Lunges, 35)
}